### ISSUE TITLE
try to use saidit.net rather than oauth.saidit.net

### ISSUE THREAD

**Issue by libertysoft3** [libertysoft3/RedReader#11]
would be nice to not have to maintain a subdomain. there on purpose?

**Comment by Mr-Steal-Your-Script** [comment]
I know this is 2 years old, but I think that this can be closed. We need to use OAuth! My API wrapper relies on OAuth! oauth.saidit.net is how it communicates with the website. OAuth makes it possible to monitor requests being made.

[The API docs](https://saidit.net/dev/api/oauth) link to [reddit's API wiki](https://github.com/reddit-archive/reddit/wiki/API) says:

>reddit requires OAuth for authentication.

You can see more reasons as to why we need OAuth [here](https://github.com/reddit-archive/reddit/wiki/OAuth2):

>OAuth2 support allows you to use reddit to authenticate on non-reddit websites and applications.

Please do not get rid of OAuth :(

**Comment by FormerlyChucks** [comment]
We need to use OAuth. oauth.saidit.net is how the API communicates with the website. OAuth makes it possible to monitor requests being made.

[The API docs](https://saidit.net/dev/api/oauth) link to [reddit's API wiki](https://github.com/reddit-archive/reddit/wiki/API), which  says:

>reddit requires OAuth for authentication.

You can see more reasons as to why we need OAuth [here](https://github.com/reddit-archive/reddit/wiki/OAuth2):

>OAuth2 support allows you to use reddit to authenticate on non-reddit websites and applications.

**Comment by libertysoft3** [comment]
This was just an idea to not require the oauth subdomain specifically. I agree getting rid of oauth would be crazy.

**Comment by libertysoft3** [comment]
weak sauce issue, closing
